version: "3"

services:
  aria2:
    image: superng6/aria2:dev
    container_name: aria2
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - SECRET=yourtoken
      - CACHE=512M
      - UT=true
      - QUIET=true
      - SMD=false
    volumes:
      - $PWD/config:/config
      - $PWD/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6800:6800
    restart: unless-stopped   
    