version: "3"

services:
  aria2:
    image: superng6/aria2
    container_name: aria2
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - SECRET=yourtoken
      - CACHE=512M
      - UpdateTracker=true
      - QUIET=true
      - RECYCLE=true
      - MOVE=true
      - SMD=false
      - ANIDIR=ani
      - MOVDIR=movies
      - TVDIR=tv
      - CUSDIR=cusdir
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6800:6800
    restart: unless-stopped   
    